import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 0 (Foundations)',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'module-0-foundations'}],
    },
    {
      type: 'category',
      label: 'Module 1 (ROS 2)',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'module-1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2 (Simulation)',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'module-2-sim'}],
    },
    {
      type: 'category',
      label: 'Module 3 (Hardware)',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'module-3-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4 (VLA)',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'module-4-vla'}],
    },

  //   {
  //     type: 'category',
  //     label: 'Module 6 (Humanoids)',
  //     collapsible: true,
  //     collapsed: true,
  //     items: [{type: 'autogenerated', dirName: 'module-6-humanoids'}],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Appendix',
  //     collapsible: true,
  //     collapsed: true,
  //     items: [{type: 'autogenerated', dirName: 'appendix'}],
  //   },
  // ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
    */
  ],
   
};

export default sidebars;
